// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakersApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211104213845_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpeakersApi.Models.Speaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Speaker");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Chilliwack",
                            Email = "jim@potter.com",
                            Employer = "BC Hydro",
                            FirstName = "Jim",
                            LastName = "Potter",
                            MobileNumber = "778-123-4567",
                            Province = "BC",
                            Specialization = "Cloud Architect"
                        },
                        new
                        {
                            ID = 2,
                            City = "Kelowna",
                            Email = "jane@douglas.com",
                            Employer = "Kelowna Company",
                            FirstName = "Jane",
                            LastName = "Douglas",
                            MobileNumber = "778-234-5678",
                            Province = "BC",
                            Specialization = "Frontend Developer"
                        },
                        new
                        {
                            ID = 3,
                            City = "Toronto",
                            Email = "tom@gardner.com",
                            Employer = "University of Toronto",
                            FirstName = "Tom",
                            LastName = "Gardner",
                            MobileNumber = "778-345-6789",
                            Province = "ON",
                            Specialization = "Backend Developer"
                        },
                        new
                        {
                            ID = 4,
                            City = "Edmonton",
                            Email = "ann@lee.com",
                            Employer = "Edmonton Company",
                            FirstName = "Ann",
                            LastName = "Lee",
                            MobileNumber = "778-456-7890",
                            Province = "AB",
                            Specialization = "Data Analyst"
                        },
                        new
                        {
                            ID = 5,
                            City = "Saskatoon",
                            Email = "james@jones.com",
                            Employer = "Saskatoon Public Library",
                            FirstName = "James",
                            LastName = "Jones",
                            MobileNumber = "778-567-8901",
                            Province = "SK",
                            Specialization = "Automation Engineer"
                        },
                        new
                        {
                            ID = 6,
                            City = "Montreal",
                            Email = "susan@taylor.com",
                            Employer = "Quebec Power Company",
                            FirstName = "Susan",
                            LastName = "Taylor",
                            MobileNumber = "778-678-9012",
                            Province = "QC",
                            Specialization = "Database Administrator"
                        },
                        new
                        {
                            ID = 7,
                            City = "Vancouver",
                            Email = "peter@white.com",
                            Employer = "BCIT",
                            FirstName = "Peter",
                            LastName = "White",
                            MobileNumber = "778-789-0123",
                            Province = "BC",
                            Specialization = "Programmer"
                        },
                        new
                        {
                            ID = 8,
                            City = "Vancouver",
                            Email = "philip@fox.com",
                            Employer = "BCIT",
                            FirstName = "Philip",
                            LastName = "Fox",
                            MobileNumber = "778-789-0123",
                            Province = "BC",
                            Specialization = "Programmer"
                        },
                        new
                        {
                            ID = 9,
                            City = "Vancouver",
                            Email = "donna@ray.com",
                            Employer = "BCIT",
                            FirstName = "Donna",
                            LastName = "Ray",
                            MobileNumber = "778-789-0123",
                            Province = "bC",
                            Specialization = "Programmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
